import type { Metadata } from "next";
import { shadcn } from '@clerk/ui/themes';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ClerkProvider , Show, SignInButton, SignUpButton, UserButton} from '@clerk/nextjs';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
         <ClerkProvider
            appearance={{
              variables : {
                colorPrimary: '#f67027f0',
              },
              theme: [ shadcn ],
            }}
         >
          {/* <header className="flex justify-end items-center p-4 gap-4 h-16"> */}
              {/* <SignInButton> */}
                
              {/* </SignInButton> */}
              {/* <SignUpButton> */}
                {/* <button className="bg-[#f67027f0] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                  Sign Up
                </button>
              </SignUpButton> */}
                {/* <Link href="/sign-up">sign up</Link> */}
           
          {/* </header> */}
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
