name: CI

on:
  push:
    branches: [main, dev]
  pull_request:

jobs:
  web:
    name: Web CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apps/web

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci
      - run: npm run lint
      - run: npm run build

  api:
    name: API CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apps/api

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci
      - run: npm run lint
      - run: npm run build
